In [70]:
import pandas as pd
import numpy as np

In [248]:
user_segment = pd.read_csv('output/tnse_data2.csv')
user_segment['LFMStr'] = user_segment['LFMScore'].apply(lambda x: "-".join(list(str(x)) ))

port_value = pd.read_csv('data/portValue.csv')
port_setting = pd.read_csv('data/portSetting.csv')

old_demographic = pd.read_csv('data/rawDataUser.csv')
del old_demographic['_id']

In [296]:
location = pd.read_csv('data/TH.txt', delimiter="\t", header=None)[[0,1,2,3]]
location.columns = ["country", "post_code", "district", "province"]
location = location.drop_duplicates(subset=['post_code'], keep='first', inplace=False)
location.head()

  country  post_code              district province
0      TH      10100  Pom Prap Sattru Phai  Bangkok
2      TH      10110               Wattana  Bangkok
3      TH      10120               Yannawa  Bangkok
5      TH      10140            Rat Burana  Bangkok
7      TH      10150       Bang Khun Thian  Bangkok

In [250]:
old_demographic.head()

,accountNo,phoneNo,riskLevel,questionRisk/sumPointRisk,questionRisk/invesmentForeign,questionRisk/lossAllMoney,questionRisk/loss,questionRisk/lossMoneyCantAccept,questionRisk/highRiskHighReturn,questionRisk/invesmentType,...,questionaire/birthDate,account/gender,account/residenceRegisterationAddress/country,account/residenceRegisterationAddress/postalCode,account/residenceRegisterationAddress/province,account/residenceRegisterationAddress/district,account/residenceRegisterationAddress/subDistrict,birthDate/day,birthDate/month,birthDate/year
0,ODI0000034,099-241-5419,5.0,39.0,1,1.0,4.0,4.0,4.0,4.0,...,1978-11-15T17:00:00.000Z,Male,ประเทศไทย,10160,กรุงเทพมหานคร,บางแค,บางแค,NaN,NaN,NaN
1,ODI0000059,091-779-8273,5.0,38.0,1,1.0,4.0,4.0,4.0,3.0,...,1995-08-23T17:00:00.000Z,Male,ประเทศไทย,11000,นนทบุรี,เมืองนนทบุรี,บางรักน้อย,NaN,NaN,NaN
2,ODI0000067,098-556-6555,4.0,22.0,1,1.0,1.0,1.0,1.0,2.0,...,1983-09-09T17:00:00.000Z,Female,ประเทศไทย,10120,กรุงเทพมหานคร,สาทร,ทุ่งวัดดอน,NaN,NaN,NaN
3,ODI0000068,081-838-3333,5.0,37.0,1,1.0,4.0,4.0,4.0,4.0,...,1986-07-21T17:00:00.000Z,Male,ประเทศไทย,10300,กรุงเทพมหานคร,ดุสิต,สวนจิตรลดา,NaN,NaN,NaN
4,ODI0000072,097-195-8555,4.0,34.0,1,1.0,4.0,4.0,3.0,4.0,...,1980-03-07T17:00:00.000Z,Male,ประเทศไทย,10250,กรุงเทพมหานคร,สวนหลวง,สวนหลวง,NaN,NaN,NaN

In [251]:
use_demographic = old_demographic[['accountNo','phoneNo', 'questionaire/birthDate','birthDate/year','account/gender','account/residenceRegisterationAddress/postalCode', 'riskLevel']]
use_demographic.head()

,accountNo,phoneNo,questionaire/birthDate,birthDate/year,account/gender,account/residenceRegisterationAddress/postalCode,riskLevel
0,ODI0000034,099-241-5419,1978-11-15T17:00:00.000Z,NaN,Male,10160,5.0
1,ODI0000059,091-779-8273,1995-08-23T17:00:00.000Z,NaN,Male,11000,5.0
2,ODI0000067,098-556-6555,1983-09-09T17:00:00.000Z,NaN,Female,10120,4.0
3,ODI0000068,081-838-3333,1986-07-21T17:00:00.000Z,NaN,Male,10300,5.0
4,ODI0000072,097-195-8555,1980-03-07T17:00:00.000Z,NaN,Male,10250,4.0

หลักของเบอร์สวย
- ตอง
- เรียง 3 ตัวขึ้นไป เช่น 123,456,567

In [252]:
import re 
from datetime import datetime

def goodTelNo(x):
    tong = ['111','222','333','444','555','666','777','888','999']
    rieng = ['012','123','234','345','456','567','678','789','890']
    for ind in range(len(tong)):
        if (tong[ind] in x) or (rieng[ind] in x):
            return "Good Number"
    return "Normal Number"

def age(x,y):
    x = str(x)
    if len(x) > 3:
        year = x[0:4]
    else:
        year = y
    
    age_num = 2019-int(year)
    if 20 <= age_num <= 24:
        return '20-24'
    elif 25 <= age_num <= 34:
        return '25-34'
    elif 35 <= age_num <= 44:
        return '35-44'
    elif 45 <= age_num :
        return '45+'
    else:
        return age_num

def provinceLocation(post_code):
    return str(post_code)[0:2]

def income(x,y):
    x = str(x)
    if len(x) > 3:
        year = x[0:4]
    else:
        year = y
    
    age_num = 2019-int(year)
    if 20 <= age_num <= 24:
        return '20-24'
    elif 25 <= age_num <= 34:
        return '25-34'
    elif 35 <= age_num <= 44:
        return '35-44'
    elif 45 <= age_num :
        return '45+'
    else:
        return age_num

In [253]:
demo = pd.DataFrame({'acc_no': use_demographic['accountNo'],
                     'tel': use_demographic['phoneNo'].apply(goodTelNo),
                     'age': use_demographic.apply(lambda row: age(row['questionaire/birthDate'], row['birthDate/year']), axis=1),
                     'gender': use_demographic['account/gender'],
                     'post_code': use_demographic['account/residenceRegisterationAddress/postalCode'],
                     'prov_code': use_demographic['account/residenceRegisterationAddress/postalCode'].apply(provinceLocation),
                     'risk_level': use_demographic['riskLevel'],
                    })

In [254]:
demo.head()

       acc_no            tel    age  gender  post_code prov_code  risk_level
0  ODI0000034  Normal Number  35-44    Male      10160        10         5.0
1  ODI0000059  Normal Number  20-24    Male      11000        11         5.0
2  ODI0000067    Good Number  35-44  Female      10120        10         4.0
3  ODI0000068    Good Number  25-34    Male      10300        10         5.0
4  ODI0000072    Good Number  35-44    Male      10250        10         4.0

In [255]:
demo.shape

(3970, 7)

In [256]:
user_111 = user_segment[user_segment['LFMScore'] == 111]
user_444 = user_segment[user_segment['LFMScore'] == 444]
user_segment.shape, user_111.shape, user_444.shape

((1833, 8), (266, 8), (113, 8))

In [304]:
segment_and_demo = pd.merge(user_segment ,demo,how='left', on='acc_no')
lastMonthRiskLevel = port_setting[port_setting['portNo'] == 'RB01'][['riskLevel','accNo']].copy()
lastMonthRiskLevel['last_risk_level'] = lastMonthRiskLevel['riskLevel']
del lastMonthRiskLevel['riskLevel']

all_merge = pd.merge(segment_and_demo, location,how='left', on='post_code')
all_merge2 = pd.merge(all_merge, lastMonthRiskLevel,how='left', left_on='acc_no', right_on='accNo')

In [305]:
all_merge2.to_csv('output/all_merge.csv', index=False)

In [306]:
all_merge2

,acc_no,LFMScore,L_quartile,F_quartile,M_quartile,tnse-x,tnse-y,LFMStr,tel,age,gender,post_code,prov_code,risk_level,country,district,province,accNo,last_risk_level
0,ODI0000034,444,4 : มากกว่า 135 วัน,4 : มากกว่า 5 ครั้ง,"4 : มากกว่า 15,261.8 บาท",282.161530,-23.804598,4-4-4,Normal Number,35-44,Male,10160.0,10,5.0,TH,Phasi Charoen,Bangkok,ODI0000034,5.0
1,ODI0000059,441,4 : มากกว่า 135 วัน,4 : มากกว่า 5 ครั้ง,"1 : ไม่เกิน 1,000 บาท",139.034910,-285.442570,4-4-1,Normal Number,20-24,Male,11000.0,11,5.0,TH,Muang Nonthaburi,Nonthaburi,ODI0000059,4.0
2,ODI0000067,444,4 : มากกว่า 135 วัน,4 : มากกว่า 5 ครั้ง,"4 : มากกว่า 15,261.8 บาท",259.053700,-27.004026,4-4-4,Good Number,35-44,Female,10120.0,10,4.0,TH,Yannawa,Bangkok,ODI0000067,4.0
3,ODI0000068,434,4 : มากกว่า 135 วัน,3 : 3-5 ครั้ง,"4 : มากกว่า 15,261.8 บาท",141.506680,-0.824704,4-3-4,Good Number,25-34,Male,10300.0,10,5.0,TH,Dusit,Bangkok,ODI0000068,5.0
4,ODI0000072,443,4 : มากกว่า 135 วัน,4 : มากกว่า 5 ครั้ง,"3 : 7,001-15,261.8 บาท",239.113050,-191.500950,4-4-3,Good Number,35-44,Male,10250.0,10,4.0,TH,Suang Luang,Bangkok,ODI0000072,5.0
5,ODI0000080,411,4 : มากกว่า 135 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-44.943480,-340.739470,4-1-1,Normal Number,25-34,Female,10230.0,10,4.0,TH,Lat Phrao,Bangkok,ODI0000080,4.0
6,ODI0000082,424,4 : มากกว่า 135 วัน,2 : 2 ครั้ง,"4 : มากกว่า 15,261.8 บาท",105.755340,-55.082027,4-2-4,Normal Number,25-34,Female,74130.0,74,5.0,NaN,NaN,NaN,ODI0000082,5.0
7,ODI0000083,411,4 : มากกว่า 135 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-44.943480,-340.739470,4-1-1,Normal Number,35-44,Male,55120.0,55,3.0,TH,Pua,Nan,ODI0000083,4.0
8,ODI0000084,111,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-229.231870,34.217587,1-1-1,Good Number,45+,Female,10900.0,10,3.0,NaN,NaN,NaN,ODI0000084,3.0
9,ODI0000086,422,4 : มากกว่า 135 วัน,2 : 2 ครั้ง,"2 : 1,001-7,000 บาท",-17.013250,-247.526170,4-2-2,Normal Number,35-44,Female,60000.0,60,3.0,TH,Muang Nakhon Sawan,Nakhon Sawan,ODI0000086,3.0
10,ODI0000089,411,4 : มากกว่า 135 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-44.943480,-340.739470,4-1-1,Normal Number,25-34,Female,10240.0,10,3.0,TH,Bang Kapi,Bangkok,ODI0000089,3.0
11,ODI0000090,111,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-229.231870,34.217587,1-1-1,Good Number,25-34,Female,11130.0,11,3.0,TH,Bang Kruai,Nonthaburi,ODI0000090,3.0
12,ODI0000091,111,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-229.231870,34.217587,1-1-1,Normal Number,25-34,Female,10540.0,10,1.0,TH,Bang Phli,Samut Prakan,ODI0000091,1.0
13,ODI0000092,442,4 : มากกว่า 135 วัน,4 : มากกว่า 5 ครั้ง,"2 : 1,001-7,000 บาท",171.207340,-283.827970,4-4-2,Normal Number,25-34,Male,73210.0,73,4.0,NaN,NaN,NaN,ODI0000092,5.0
14,ODI0000097,444,4 : มากกว่า 135 วัน,4 : มากกว่า 5 ครั้ง,"4 : มากกว่า 15,261.8 บาท",265.314400,8.532092,4-4-4,Normal Number,45+,Male,10500.0,10,NaN,TH,Bang Rak,Bangkok,ODI0000097,3.0
15,ODI0000099,211,2 : 38-90 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-252.569210,-160.757870,2-1-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ODI0000099,2.0
16,ODI0000103,211,2 : 38-90 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-217.217590,-166.334980,2-1-1,Normal Number,25-34,Male,30170.0,30,3.0,TH,Sung Noen,Nakhon Ratchasima,ODI0000103,3.0
17,ODI0000104,111,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-229.231870,34.217587,1-1-1,Good Number,35-44,Male,10120.0,10,4.0,TH,Yannawa,Bangkok,ODI0000104,4.0
18,ODI0000128,431,4 : มากกว่า 135 วัน,3 : 3-5 ครั้ง,"1 : ไม่เกิน 1,000 บาท",52.965744,-315.003720,4-3-1,Normal Number,25-34,Male,66120.0,66,4.0,TH,Bang Mun Nak,Phichit,ODI0000128,4.0
19,ODI0000129,311,3 : 91-135 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-172.986200,-284.899080,3-1-1,Normal Number,25-34,Male,57340.0,57,3.0,TH,Khun Tan,Chiang Rai,ODI0000129,3.0
20,ODI0000130,422,4 : มากกว่า 135 วัน,2 : 2 ครั้ง,"2 : 1,001-7,000 บาท",-17.013250,-247.526170,4-2-2,Good Number,35-44,Male,10900.0,10,3.0,NaN,NaN,NaN,ODI0000130,3.0
21,ODI0000134,323,3 : 91-135 วัน,2 : 2 ครั้ง,"3 : 7,001-15,261.8 บาท",40.331740,-3.338461,3-2-3,Normal Number,25-34,Female,11000.0,11,4.0,TH,Muang Nonthaburi,Nonthaburi,ODI0000134,4.0
22,ODI0000135,444,4 : มากกว่า 135 วัน,4 : มากกว่า 5 ครั้ง,"4 : มากกว่า 15,261.8 บาท",265.314400,8.532092,4-4-4,Normal Number,20-24,Male,36110.0,36,1.0,TH,Phu Khieo,Chaiyaphum,ODI0000135,5.0
23,ODI0000140,443,4 : มากกว่า 135 วัน,4 : มากกว่า 5 ครั้ง,"3 : 7,001-15,261.8 บาท",235.580960,-224.557250,4-4-3,Normal Number,35-44,Male,42230.0,42,5.0,TH,Phu Luang,Loei,ODI0000140,4.0
24,ODI0000146,411,4 : มากกว่า 135 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-44.943480,-340.739470,4-1-1,Normal Number,25-34,Male,10250.0,10,4.0,TH,Suang Luang,Bangkok,ODI0000146,4.0
25,ODI0000147,444,4 : มากกว่า 135 วัน,4 : มากกว่า 5 ครั้ง,"4 : มากกว่า 15,261.8 บาท",265.314400,8.532092,4-4-4,Good Number,45+,Female,10160.0,10,3.0,TH,Phasi Charoen,Bangkok,ODI0000147,4.0
26,ODI0000151,444,4 : มากกว่า 135 วัน,4 : มากกว่า 5 ครั้ง,"4 : มากกว่า 15,261.8 บาท",265.314400,8.532092,4-4-4,Normal Number,45+,Female,11120.0,11,4.0,TH,Pak Kret,Nonthaburi,ODI0000151,4.0
27,ODI0000162,412,4 : มากกว่า 135 วัน,1 : 1 ครั้ง,"2 : 1,001-7,000 บาท",-5.423209,-184.724240,4-1-2,Normal Number,25-34,Male,10900.0,10,4.0,NaN,NaN,NaN,ODI0000162,4.0
28,ODI0000164,334,3 : 91-135 วัน,3 : 3-5 ครั้ง,"4 : มากกว่า 15,261.8 บาท",166.103270,99.620580,3-3-4,Good Number,25-34,Male,12130.0,12,4.0,NaN,NaN,NaN,ODI0000164,4.0
29,ODI0000166,332,3 : 91-135 วัน,3 : 3-5 ครั้ง,"2 : 1,001-7,000 บาท",85.473210,-198.911100,3-3-2,Normal Number,35-44,Female,10210.0,10,3.0,TH,Lak Si,Bangkok,ODI0000166,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1803,ODI0019202,111,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-182.243480,13.583644,1-1-1,Normal Number,25-34,Male,57000.0,57,3.0,TH,Muang Chiang Rai,Chiang Rai,ODI0019202,3.0
1804,ODI0019240,111,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-182.243480,13.583644,1-1-1,Normal Number,35-44,Female,10250.0,10,3.0,TH,Suang Luang,Bangkok,ODI0019240,3.0
1805,ODI0019243,111,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-182.243480,13.583644,1-1-1,Normal Number,25-34,Male,11000.0,11,3.0,TH,Muang Nonthaburi,Nonthaburi,ODI0019243,3.0
1806,ODI0019244,112,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"2 : 1,001-7,000 บาท",-73.857346,328.017730,1-1-2,Normal Number,25-34,Male,10150.0,10,3.0,TH,Bang Khun Thian,Bangkok,ODI0019244,3.0
1807,ODI0019280,123,1 : ไม่เกิน 37 วัน,2 : 2 ครั้ง,"3 : 7,001-15,261.8 บาท",-11.243987,177.469910,1-2-3,Normal Number,35-44,Male,10210.0,10,4.0,TH,Lak Si,Bangkok,ODI0019280,4.0
1808,ODI0019294,122,1 : ไม่เกิน 37 วัน,2 : 2 ครั้ง,"2 : 1,001-7,000 บาท",-78.337220,110.639915,1-2-2,Normal Number,35-44,Male,21000.0,21,5.0,TH,Muang Rayong,Rayong,ODI0019294,5.0
1809,ODI0019306,111,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-182.243480,13.583644,1-1-1,Normal Number,25-34,Female,10210.0,10,4.0,TH,Lak Si,Bangkok,ODI0019306,4.0
1810,ODI0019310,114,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"4 : มากกว่า 15,261.8 บาท",-142.920320,233.130630,1-1-4,Normal Number,25-34,Male,33140.0,33,2.0,TH,Khukhan,Sisaket,ODI0019310,2.0
1811,ODI0019332,111,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-182.243480,13.583644,1-1-1,Normal Number,25-34,Male,12130.0,12,2.0,NaN,NaN,NaN,ODI0019332,2.0
1812,ODI0019371,111,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-182.243480,13.583644,1-1-1,Normal Number,35-44,Male,11110.0,11,4.0,TH,Bang Bua Thong,Nonthaburi,ODI0019371,4.0
1813,ODI0019394,112,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"2 : 1,001-7,000 บาท",-73.857346,328.017730,1-1-2,Normal Number,20-24,Male,65000.0,65,3.0,TH,Muang Phitsanulok,Phitsanulok,ODI0019394,4.0
1814,ODI0019398,114,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"4 : มากกว่า 15,261.8 บาท",-142.920320,233.130630,1-1-4,Normal Number,25-34,Male,10400.0,10,3.0,TH,Ding Daeng,Bangkok,ODI0019398,3.0
1815,ODI0019400,111,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-182.243480,13.583644,1-1-1,Normal Number,25-34,Male,25000.0,25,2.0,TH,Muang Prachinburi,Prachinburi,ODI0019400,2.0
1816,ODI0019465,114,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"4 : มากกว่า 15,261.8 บาท",-142.920320,233.130630,1-1-4,Normal Number,35-44,Male,10800.0,10,4.0,TH,Bang Su,Bangkok,ODI0019465,4.0
1817,ODI0019472,113,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"3 : 7,001-15,261.8 บาท",-189.649640,265.948580,1-1-3,Normal Number,25-34,Male,10250.0,10,4.0,TH,Suang Luang,Bangkok,ODI0019472,4.0
1818,ODI0019479,112,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"2 : 1,001-7,000 บาท",-73.857346,328.017730,1-1-2,Normal Number,20-24,Male,11000.0,11,3.0,TH,Muang Nonthaburi,Nonthaburi,ODI0019479,4.0
1819,ODI0019556,112,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"2 : 1,001-7,000 บาท",-101.838110,316.247160,1-1-2,Normal Number,25-34,Male,30170.0,30,3.0,TH,Sung Noen,Nakhon Ratchasima,ODI0019556,3.0
1820,ODI0019558,111,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-182.243480,13.583644,1-1-1,Normal Number,35-44,Female,50230.0,50,4.0,TH,Hang Dong,Chiang Mai,ODI0019558,5.0
1821,ODI0019578,112,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"2 : 1,001-7,000 บาท",-101.838110,316.247160,1-1-2,Good Number,25-34,Female,10530.0,10,3.0,TH,Nong Chok,Bangkok,ODI0019578,4.0
1822,ODI0019587,114,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"4 : มากกว่า 15,261.8 บาท",-142.920320,233.130630,1-1-4,Normal Number,20-24,Female,11110.0,11,3.0,TH,Bang Bua Thong,Nonthaburi,ODI0019587,3.0
1823,ODI0019655,122,1 : ไม่เกิน 37 วัน,2 : 2 ครั้ง,"2 : 1,001-7,000 บาท",-78.363365,139.384780,1-2-2,Normal Number,25-34,Male,10140.0,10,3.0,TH,Rat Burana,Bangkok,ODI0019655,3.0
1824,ODI0019660,114,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"4 : มากกว่า 15,261.8 บาท",-142.920320,233.130630,1-1-4,Normal Number,25-34,Male,10100.0,10,3.0,TH,Pom Prap Sattru Phai,Bangkok,ODI0019660,4.0
1825,ODI0019678,114,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"4 : มากกว่า 15,261.8 บาท",-142.920320,233.130630,1-1-4,Normal Number,35-44,Male,21210.0,21,3.0,TH,Wang Chan,Rayong,ODI0019678,3.0
1826,ODI0019680,111,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-182.243480,13.583644,1-1-1,Normal Number,45+,Male,10220.0,10,3.0,TH,Bang Khen,Bangkok,ODI0019680,3.0
1827,ODI0019720,123,1 : ไม่เกิน 37 วัน,2 : 2 ครั้ง,"3 : 7,001-15,261.8 บาท",5.290573,172.835100,1-2-3,Normal Number,25-34,Male,10220.0,10,2.0,TH,Bang Khen,Bangkok,ODI0019720,1.0
1828,ODI0019727,112,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"2 : 1,001-7,000 บาท",-101.838110,316.247160,1-1-2,Normal Number,25-34,Male,10400.0,10,3.0,TH,Ding Daeng,Bangkok,ODI0019727,3.0
1829,ODI0019754,112,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"2 : 1,001-7,000 บาท",-101.838110,316.247160,1-1-2,Normal Number,25-34,Female,10900.0,10,3.0,NaN,NaN,NaN,ODI0019754,4.0
1830,ODI0019777,113,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"3 : 7,001-15,261.8 บาท",-189.649640,265.948580,1-1-3,Normal Number,35-44,Male,10900.0,10,4.0,NaN,NaN,NaN,ODI0019777,4.0
1831,ODI0019847,112,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"2 : 1,001-7,000 บาท",-101.838110,316.247160,1-1-2,Normal Number,25-34,Male,10210.0,10,4.0,TH,Lak Si,Bangkok,ODI0019847,1.0
1832,ODI0019860,111,1 : ไม่เกิน 37 วัน,1 : 1 ครั้ง,"1 : ไม่เกิน 1,000 บาท",-229.231870,34.217587,1-1-1,Normal Number,35-44,Male,10400.0,10,3.0,TH,Ding Daeng,Bangkok,ODI0019860,3.0